/* Auto-generated by genmsg_cpp for file /home/pedro/ros/asctec/main_control/msg/imu_acc.msg */
#ifndef MAIN_CONTROL_MESSAGE_IMU_ACC_H
#define MAIN_CONTROL_MESSAGE_IMU_ACC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace main_control
{
template <class ContainerAllocator>
struct imu_acc_ {
  typedef imu_acc_<ContainerAllocator> Type;

  imu_acc_()
  : header()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , accx(0.0)
  , accy(0.0)
  , accz(0.0)
  {
  }

  imu_acc_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , accx(0.0)
  , accy(0.0)
  , accz(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;

  typedef double _accx_type;
  double accx;

  typedef double _accy_type;
  double accy;

  typedef double _accz_type;
  double accz;


  typedef boost::shared_ptr< ::main_control::imu_acc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_control::imu_acc_<ContainerAllocator>  const> ConstPtr;
}; // struct imu_acc
typedef  ::main_control::imu_acc_<std::allocator<void> > imu_acc;

typedef boost::shared_ptr< ::main_control::imu_acc> imu_accPtr;
typedef boost::shared_ptr< ::main_control::imu_acc const> imu_accConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::main_control::imu_acc_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::main_control::imu_acc_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace main_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::main_control::imu_acc_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::main_control::imu_acc_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::main_control::imu_acc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3ca53098196b401da5f9fd4ff78dc3c8";
  }

  static const char* value(const  ::main_control::imu_acc_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3ca53098196b401dULL;
  static const uint64_t static_value2 = 0xa5f9fd4ff78dc3c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::main_control::imu_acc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "main_control/imu_acc";
  }

  static const char* value(const  ::main_control::imu_acc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::main_control::imu_acc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
float64 accx\n\
float64 accy\n\
float64 accz\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::main_control::imu_acc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::main_control::imu_acc_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::main_control::imu_acc_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::main_control::imu_acc_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.accx);
    stream.next(m.accy);
    stream.next(m.accz);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct imu_acc_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_control::imu_acc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::main_control::imu_acc_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "accx: ";
    Printer<double>::stream(s, indent + "  ", v.accx);
    s << indent << "accy: ";
    Printer<double>::stream(s, indent + "  ", v.accy);
    s << indent << "accz: ";
    Printer<double>::stream(s, indent + "  ", v.accz);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MAIN_CONTROL_MESSAGE_IMU_ACC_H

