/* Auto-generated by genmsg_cpp for file /home/pedro/ros/asctec/main_control/msg/string_stamped.msg */
#ifndef MAIN_CONTROL_MESSAGE_STRING_STAMPED_H
#define MAIN_CONTROL_MESSAGE_STRING_STAMPED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace main_control
{
template <class ContainerAllocator>
struct string_stamped_ {
  typedef string_stamped_<ContainerAllocator> Type;

  string_stamped_()
  : header()
  , data()
  {
  }

  string_stamped_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  data;


  typedef boost::shared_ptr< ::main_control::string_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_control::string_stamped_<ContainerAllocator>  const> ConstPtr;
}; // struct string_stamped
typedef  ::main_control::string_stamped_<std::allocator<void> > string_stamped;

typedef boost::shared_ptr< ::main_control::string_stamped> string_stampedPtr;
typedef boost::shared_ptr< ::main_control::string_stamped const> string_stampedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::main_control::string_stamped_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::main_control::string_stamped_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace main_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::main_control::string_stamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::main_control::string_stamped_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::main_control::string_stamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c99a9440709e4d4a9716d55b8270d5e7";
  }

  static const char* value(const  ::main_control::string_stamped_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc99a9440709e4d4aULL;
  static const uint64_t static_value2 = 0x9716d55b8270d5e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::main_control::string_stamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "main_control/string_stamped";
  }

  static const char* value(const  ::main_control::string_stamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::main_control::string_stamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::main_control::string_stamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::main_control::string_stamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::main_control::string_stamped_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::main_control::string_stamped_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct string_stamped_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_control::string_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::main_control::string_stamped_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MAIN_CONTROL_MESSAGE_STRING_STAMPED_H

