/* Auto-generated by genmsg_cpp for file /home/pedro/ros/height_quad/msg/EstimateMulti.msg */
#ifndef HEIGHT_QUAD_MESSAGE_ESTIMATEMULTI_H
#define HEIGHT_QUAD_MESSAGE_ESTIMATEMULTI_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "height_quad/Estimate.h"

namespace height_quad
{
template <class ContainerAllocator>
struct EstimateMulti_ {
  typedef EstimateMulti_<ContainerAllocator> Type;

  EstimateMulti_()
  : header()
  , estimates()
  , relative_on(0)
  {
  }

  EstimateMulti_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , estimates(_alloc)
  , relative_on(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::height_quad::Estimate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::height_quad::Estimate_<ContainerAllocator> >::other >  _estimates_type;
  std::vector< ::height_quad::Estimate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::height_quad::Estimate_<ContainerAllocator> >::other >  estimates;

  typedef int8_t _relative_on_type;
  int8_t relative_on;


  typedef boost::shared_ptr< ::height_quad::EstimateMulti_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::height_quad::EstimateMulti_<ContainerAllocator>  const> ConstPtr;
}; // struct EstimateMulti
typedef  ::height_quad::EstimateMulti_<std::allocator<void> > EstimateMulti;

typedef boost::shared_ptr< ::height_quad::EstimateMulti> EstimateMultiPtr;
typedef boost::shared_ptr< ::height_quad::EstimateMulti const> EstimateMultiConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::height_quad::EstimateMulti_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::height_quad::EstimateMulti_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace height_quad

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::height_quad::EstimateMulti_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::height_quad::EstimateMulti_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::height_quad::EstimateMulti_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ba869d9da0e26b7e01d4a406b2b4ae60";
  }

  static const char* value(const  ::height_quad::EstimateMulti_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xba869d9da0e26b7eULL;
  static const uint64_t static_value2 = 0x01d4a406b2b4ae60ULL;
};

template<class ContainerAllocator>
struct DataType< ::height_quad::EstimateMulti_<ContainerAllocator> > {
  static const char* value() 
  {
    return "height_quad/EstimateMulti";
  }

  static const char* value(const  ::height_quad::EstimateMulti_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::height_quad::EstimateMulti_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
Estimate[] estimates\n\
int8 relative_on\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: height_quad/Estimate\n\
std_msgs/String             name\n\
geometry_msgs/Vector3       position\n\
geometry_msgs/Vector3       velocity\n\
geometry_msgs/Vector3       perturbation\n\
geometry_msgs/Quaternion    orientation\n\
int8                        updated\n\
float64[]                   covariance\n\
std_msgs/String             sensors\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::height_quad::EstimateMulti_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::height_quad::EstimateMulti_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::height_quad::EstimateMulti_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::height_quad::EstimateMulti_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.estimates);
    stream.next(m.relative_on);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EstimateMulti_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::height_quad::EstimateMulti_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::height_quad::EstimateMulti_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "estimates[]" << std::endl;
    for (size_t i = 0; i < v.estimates.size(); ++i)
    {
      s << indent << "  estimates[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::height_quad::Estimate_<ContainerAllocator> >::stream(s, indent + "    ", v.estimates[i]);
    }
    s << indent << "relative_on: ";
    Printer<int8_t>::stream(s, indent + "  ", v.relative_on);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HEIGHT_QUAD_MESSAGE_ESTIMATEMULTI_H

