// Generated by gencpp from file height/full_pose.msg
// DO NOT EDIT!


#ifndef HEIGHT_MESSAGE_FULL_POSE_H
#define HEIGHT_MESSAGE_FULL_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <height/Attitude.h>

namespace height
{
template <class ContainerAllocator>
struct full_pose_
{
  typedef full_pose_<ContainerAllocator> Type;

  full_pose_()
    : header()
    , ang_vel()
    , lin_acc()
    , attitude()
    , z(0.0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , quality(0)  {
    }
  full_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ang_vel(_alloc)
    , lin_acc(_alloc)
    , attitude(_alloc)
    , z(0.0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)
    , quality(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ang_vel_type;
  _ang_vel_type ang_vel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _lin_acc_type;
  _lin_acc_type lin_acc;

   typedef  ::height::Attitude_<ContainerAllocator>  _attitude_type;
  _attitude_type attitude;

   typedef double _z_type;
  _z_type z;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef int8_t _quality_type;
  _quality_type quality;




  typedef boost::shared_ptr< ::height::full_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::height::full_pose_<ContainerAllocator> const> ConstPtr;

}; // struct full_pose_

typedef ::height::full_pose_<std::allocator<void> > full_pose;

typedef boost::shared_ptr< ::height::full_pose > full_posePtr;
typedef boost::shared_ptr< ::height::full_pose const> full_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::height::full_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::height::full_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace height

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/indigo/share/mavros_msgs/cmake/../msg'], 'height': ['/home/pedro/catkin/src/height/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::height::full_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::height::full_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::height::full_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::height::full_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::height::full_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::height::full_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::height::full_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3ec521dd8d5d73781ebeb348bf58cdb";
  }

  static const char* value(const ::height::full_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3ec521dd8d5d737ULL;
  static const uint64_t static_value2 = 0x81ebeb348bf58cdbULL;
};

template<class ContainerAllocator>
struct DataType< ::height::full_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "height/full_pose";
  }

  static const char* value(const ::height::full_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::height::full_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Vector3 ang_vel\n\
geometry_msgs/Vector3 lin_acc\n\
Attitude attitude\n\
float64 z\n\
float64 x\n\
float64 y\n\
float64 vx\n\
float64 vy\n\
int8 quality\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: height/Attitude\n\
float64 yaw\n\
float64 pitch\n\
float64 roll\n\
";
  }

  static const char* value(const ::height::full_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::height::full_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ang_vel);
      stream.next(m.lin_acc);
      stream.next(m.attitude);
      stream.next(m.z);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct full_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::height::full_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::height::full_pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ang_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_vel);
    s << indent << "lin_acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.lin_acc);
    s << indent << "attitude: ";
    s << std::endl;
    Printer< ::height::Attitude_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEIGHT_MESSAGE_FULL_POSE_H
