(cl:in-package rab3D-msg)
(cl:export '(SLOT-VAL
          SLOT
          CODE-VAL
          CODE
          ADC1-VAL
          ADC1
          ADC2-VAL
          ADC2
          ADC3-VAL
          ADC3
          ADC4-VAL
          ADC4
          ADC5-VAL
          ADC5
          ADC6-VAL
          ADC6
          ADC7-VAL
          ADC7
          ADC8-VAL
          ADC8
          ADC9-VAL
          ADC9
          ADC10-VAL
          ADC10
          ADC11-VAL
          ADC11
          ADC12-VAL
          ADC12
          ADC13-VAL
          ADC13
          ADC14-VAL
          ADC14
          ADC15-VAL
          ADC15
          ADC16-VAL
          ADC16
))