/* Auto-generated by genmsg_cpp for file /home/pedro/ros/asctec/main_control/msg/state_command.msg */
#ifndef MAIN_CONTROL_MESSAGE_STATE_COMMAND_H
#define MAIN_CONTROL_MESSAGE_STATE_COMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"
#include "geometry_msgs/Vector3.h"
#include "geometry_msgs/Vector3.h"

namespace main_control
{
template <class ContainerAllocator>
struct state_command_ {
  typedef state_command_<ContainerAllocator> Type;

  state_command_()
  : header()
  , position()
  , velocity()
  , acceleration()
  , yaw(0.0)
  , yaw_rate(0.0)
  , pos_on(0)
  , yaw_rate_on(0)
  , relative_on(0)
  {
  }

  state_command_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , position(_alloc)
  , velocity(_alloc)
  , acceleration(_alloc)
  , yaw(0.0)
  , yaw_rate(0.0)
  , pos_on(0)
  , yaw_rate_on(0)
  , relative_on(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  position;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  velocity;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  acceleration;

  typedef double _yaw_type;
  double yaw;

  typedef double _yaw_rate_type;
  double yaw_rate;

  typedef int8_t _pos_on_type;
  int8_t pos_on;

  typedef int8_t _yaw_rate_on_type;
  int8_t yaw_rate_on;

  typedef int8_t _relative_on_type;
  int8_t relative_on;


  typedef boost::shared_ptr< ::main_control::state_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main_control::state_command_<ContainerAllocator>  const> ConstPtr;
}; // struct state_command
typedef  ::main_control::state_command_<std::allocator<void> > state_command;

typedef boost::shared_ptr< ::main_control::state_command> state_commandPtr;
typedef boost::shared_ptr< ::main_control::state_command const> state_commandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::main_control::state_command_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::main_control::state_command_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace main_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::main_control::state_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::main_control::state_command_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::main_control::state_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "91e5adc2b2b2b5ce5be7aa8d7ca96985";
  }

  static const char* value(const  ::main_control::state_command_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x91e5adc2b2b2b5ceULL;
  static const uint64_t static_value2 = 0x5be7aa8d7ca96985ULL;
};

template<class ContainerAllocator>
struct DataType< ::main_control::state_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "main_control/state_command";
  }

  static const char* value(const  ::main_control::state_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::main_control::state_command_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
geometry_msgs/Vector3       position\n\
geometry_msgs/Vector3       velocity\n\
geometry_msgs/Vector3       acceleration\n\
\n\
float64 yaw\n\
float64 yaw_rate\n\
\n\
int8 pos_on\n\
int8 yaw_rate_on\n\
int8 relative_on\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::main_control::state_command_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::main_control::state_command_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::main_control::state_command_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::main_control::state_command_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.position);
    stream.next(m.velocity);
    stream.next(m.acceleration);
    stream.next(m.yaw);
    stream.next(m.yaw_rate);
    stream.next(m.pos_on);
    stream.next(m.yaw_rate_on);
    stream.next(m.relative_on);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct state_command_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main_control::state_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::main_control::state_command_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "pos_on: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pos_on);
    s << indent << "yaw_rate_on: ";
    Printer<int8_t>::stream(s, indent + "  ", v.yaw_rate_on);
    s << indent << "relative_on: ";
    Printer<int8_t>::stream(s, indent + "  ", v.relative_on);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MAIN_CONTROL_MESSAGE_STATE_COMMAND_H

