# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from height_quad/EstimateSingle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import height_quad.msg
import std_msgs.msg

class EstimateSingle(genpy.Message):
  _md5sum = "aa91808c4d02906ac29fbe291106ae05"
  _type = "height_quad/EstimateSingle"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
Estimate estimate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: height_quad/Estimate
std_msgs/String             name
geometry_msgs/Vector3       position
geometry_msgs/Vector3       velocity
geometry_msgs/Vector3       perturbation
geometry_msgs/Quaternion    orientation
int8                        updated
float64[]                   covariance
std_msgs/String             sensors

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['header','estimate']
  _slot_types = ['std_msgs/Header','height_quad/Estimate']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,estimate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EstimateSingle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.estimate is None:
        self.estimate = height_quad.msg.Estimate()
    else:
      self.header = std_msgs.msg.Header()
      self.estimate = height_quad.msg.Estimate()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.estimate.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_13db.pack(_x.estimate.position.x, _x.estimate.position.y, _x.estimate.position.z, _x.estimate.velocity.x, _x.estimate.velocity.y, _x.estimate.velocity.z, _x.estimate.perturbation.x, _x.estimate.perturbation.y, _x.estimate.perturbation.z, _x.estimate.orientation.x, _x.estimate.orientation.y, _x.estimate.orientation.z, _x.estimate.orientation.w, _x.estimate.updated))
      length = len(self.estimate.covariance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.estimate.covariance))
      _x = self.estimate.sensors.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.estimate is None:
        self.estimate = height_quad.msg.Estimate()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.estimate.name.data = str[start:end].decode('utf-8')
      else:
        self.estimate.name.data = str[start:end]
      _x = self
      start = end
      end += 105
      (_x.estimate.position.x, _x.estimate.position.y, _x.estimate.position.z, _x.estimate.velocity.x, _x.estimate.velocity.y, _x.estimate.velocity.z, _x.estimate.perturbation.x, _x.estimate.perturbation.y, _x.estimate.perturbation.z, _x.estimate.orientation.x, _x.estimate.orientation.y, _x.estimate.orientation.z, _x.estimate.orientation.w, _x.estimate.updated,) = _struct_13db.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.estimate.covariance = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.estimate.sensors.data = str[start:end].decode('utf-8')
      else:
        self.estimate.sensors.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.estimate.name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_13db.pack(_x.estimate.position.x, _x.estimate.position.y, _x.estimate.position.z, _x.estimate.velocity.x, _x.estimate.velocity.y, _x.estimate.velocity.z, _x.estimate.perturbation.x, _x.estimate.perturbation.y, _x.estimate.perturbation.z, _x.estimate.orientation.x, _x.estimate.orientation.y, _x.estimate.orientation.z, _x.estimate.orientation.w, _x.estimate.updated))
      length = len(self.estimate.covariance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.estimate.covariance.tostring())
      _x = self.estimate.sensors.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.estimate is None:
        self.estimate = height_quad.msg.Estimate()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.estimate.name.data = str[start:end].decode('utf-8')
      else:
        self.estimate.name.data = str[start:end]
      _x = self
      start = end
      end += 105
      (_x.estimate.position.x, _x.estimate.position.y, _x.estimate.position.z, _x.estimate.velocity.x, _x.estimate.velocity.y, _x.estimate.velocity.z, _x.estimate.perturbation.x, _x.estimate.perturbation.y, _x.estimate.perturbation.z, _x.estimate.orientation.x, _x.estimate.orientation.y, _x.estimate.orientation.z, _x.estimate.orientation.w, _x.estimate.updated,) = _struct_13db.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.estimate.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.estimate.sensors.data = str[start:end].decode('utf-8')
      else:
        self.estimate.sensors.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_13db = struct.Struct("<13db")
