/* Auto-generated by genmsg_cpp for file /home/ubuntu/ros/quad_control_rosbuild/quad_msgs/msg/MultiPose.msg */
#ifndef QUAD_MSGS_MESSAGE_MULTIPOSE_H
#define QUAD_MSGS_MESSAGE_MULTIPOSE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "quad_msgs/SinglePose.h"

namespace quad_msgs
{
template <class ContainerAllocator>
struct MultiPose_ {
  typedef MultiPose_<ContainerAllocator> Type;

  MultiPose_()
  : header()
  , poses()
  {
  }

  MultiPose_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , poses(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::quad_msgs::SinglePose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::quad_msgs::SinglePose_<ContainerAllocator> >::other >  _poses_type;
  std::vector< ::quad_msgs::SinglePose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::quad_msgs::SinglePose_<ContainerAllocator> >::other >  poses;


  typedef boost::shared_ptr< ::quad_msgs::MultiPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::MultiPose_<ContainerAllocator>  const> ConstPtr;
}; // struct MultiPose
typedef  ::quad_msgs::MultiPose_<std::allocator<void> > MultiPose;

typedef boost::shared_ptr< ::quad_msgs::MultiPose> MultiPosePtr;
typedef boost::shared_ptr< ::quad_msgs::MultiPose const> MultiPoseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quad_msgs::MultiPose_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quad_msgs::MultiPose_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quad_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quad_msgs::MultiPose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quad_msgs::MultiPose_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::MultiPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e14cd22ab2349681fc355becb7328751";
  }

  static const char* value(const  ::quad_msgs::MultiPose_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe14cd22ab2349681ULL;
  static const uint64_t static_value2 = 0xfc355becb7328751ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::MultiPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quad_msgs/MultiPose";
  }

  static const char* value(const  ::quad_msgs::MultiPose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::MultiPose_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
SinglePose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: quad_msgs/SinglePose\n\
string name\n\
geometry_msgs/Point position\n\
geometry_msgs/Quaternion orientation\n\
int8 pose_updated\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::quad_msgs::MultiPose_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quad_msgs::MultiPose_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quad_msgs::MultiPose_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quad_msgs::MultiPose_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.poses);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MultiPose_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::MultiPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quad_msgs::MultiPose_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::quad_msgs::SinglePose_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_MULTIPOSE_H

