/* Auto-generated by genmsg_cpp for file /home/ubuntu/ros/quad_control_rosbuild/quad_msgs/msg/CamDet.msg */
#ifndef QUAD_MSGS_MESSAGE_CAMDET_H
#define QUAD_MSGS_MESSAGE_CAMDET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"

namespace quad_msgs
{
template <class ContainerAllocator>
struct CamDet_ {
  typedef CamDet_<ContainerAllocator> Type;

  CamDet_()
  : header()
  , blob()
  {
  }

  CamDet_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , blob(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _blob_type;
  std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  blob;


  typedef boost::shared_ptr< ::quad_msgs::CamDet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::CamDet_<ContainerAllocator>  const> ConstPtr;
}; // struct CamDet
typedef  ::quad_msgs::CamDet_<std::allocator<void> > CamDet;

typedef boost::shared_ptr< ::quad_msgs::CamDet> CamDetPtr;
typedef boost::shared_ptr< ::quad_msgs::CamDet const> CamDetConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quad_msgs::CamDet_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quad_msgs::CamDet_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quad_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quad_msgs::CamDet_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quad_msgs::CamDet_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::CamDet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ed5d3ef4dd39cff355876f8d615e3b66";
  }

  static const char* value(const  ::quad_msgs::CamDet_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xed5d3ef4dd39cff3ULL;
  static const uint64_t static_value2 = 0x55876f8d615e3b66ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::CamDet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quad_msgs/CamDet";
  }

  static const char* value(const  ::quad_msgs::CamDet_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::CamDet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
geometry_msgs/Point[] blob\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::quad_msgs::CamDet_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quad_msgs::CamDet_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quad_msgs::CamDet_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quad_msgs::CamDet_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.blob);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CamDet_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::CamDet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quad_msgs::CamDet_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "blob[]" << std::endl;
    for (size_t i = 0; i < v.blob.size(); ++i)
    {
      s << indent << "  blob[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.blob[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_CAMDET_H

