# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rab3D/Rab3DObj.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Rab3DObj(genpy.Message):
  _md5sum = "24f96da6018bfad44f2cacae52c1832b"
  _type = "rab3D/Rab3DObj"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 slot
int32 code
int16 adc1
int16 adc2
int16 adc3
int16 adc4
int16 adc5
int16 adc6
int16 adc7
int16 adc8
int16 adc9
int16 adc10
int16 adc11
int16 adc12
int16 adc13
int16 adc14
int16 adc15
int16 adc16


"""
  __slots__ = ['slot','code','adc1','adc2','adc3','adc4','adc5','adc6','adc7','adc8','adc9','adc10','adc11','adc12','adc13','adc14','adc15','adc16']
  _slot_types = ['int16','int32','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       slot,code,adc1,adc2,adc3,adc4,adc5,adc6,adc7,adc8,adc9,adc10,adc11,adc12,adc13,adc14,adc15,adc16

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rab3DObj, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.slot is None:
        self.slot = 0
      if self.code is None:
        self.code = 0
      if self.adc1 is None:
        self.adc1 = 0
      if self.adc2 is None:
        self.adc2 = 0
      if self.adc3 is None:
        self.adc3 = 0
      if self.adc4 is None:
        self.adc4 = 0
      if self.adc5 is None:
        self.adc5 = 0
      if self.adc6 is None:
        self.adc6 = 0
      if self.adc7 is None:
        self.adc7 = 0
      if self.adc8 is None:
        self.adc8 = 0
      if self.adc9 is None:
        self.adc9 = 0
      if self.adc10 is None:
        self.adc10 = 0
      if self.adc11 is None:
        self.adc11 = 0
      if self.adc12 is None:
        self.adc12 = 0
      if self.adc13 is None:
        self.adc13 = 0
      if self.adc14 is None:
        self.adc14 = 0
      if self.adc15 is None:
        self.adc15 = 0
      if self.adc16 is None:
        self.adc16 = 0
    else:
      self.slot = 0
      self.code = 0
      self.adc1 = 0
      self.adc2 = 0
      self.adc3 = 0
      self.adc4 = 0
      self.adc5 = 0
      self.adc6 = 0
      self.adc7 = 0
      self.adc8 = 0
      self.adc9 = 0
      self.adc10 = 0
      self.adc11 = 0
      self.adc12 = 0
      self.adc13 = 0
      self.adc14 = 0
      self.adc15 = 0
      self.adc16 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_hi16h.pack(_x.slot, _x.code, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.adc5, _x.adc6, _x.adc7, _x.adc8, _x.adc9, _x.adc10, _x.adc11, _x.adc12, _x.adc13, _x.adc14, _x.adc15, _x.adc16))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 38
      (_x.slot, _x.code, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.adc5, _x.adc6, _x.adc7, _x.adc8, _x.adc9, _x.adc10, _x.adc11, _x.adc12, _x.adc13, _x.adc14, _x.adc15, _x.adc16,) = _struct_hi16h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_hi16h.pack(_x.slot, _x.code, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.adc5, _x.adc6, _x.adc7, _x.adc8, _x.adc9, _x.adc10, _x.adc11, _x.adc12, _x.adc13, _x.adc14, _x.adc15, _x.adc16))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 38
      (_x.slot, _x.code, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.adc5, _x.adc6, _x.adc7, _x.adc8, _x.adc9, _x.adc10, _x.adc11, _x.adc12, _x.adc13, _x.adc14, _x.adc15, _x.adc16,) = _struct_hi16h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_hi16h = struct.Struct("<hi16h")
